# highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "泮关森的博客"
markdown: redcarpet


navigations:
  - title: Blog
    class: fa fa-list-ul
    href: /blog.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  # - title: Subscribe
  #   class: fa fa-rss
  #   href: https://github.com/godpan

