markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "泮"
markdown: rdiscount

# author: "wayne"
# atom-baseurl: "http://lhzhang.com"
# disqus: "gopherwood"

navigations:
  - title: Blog
    class: fa fa-list-ul
    href: /blog.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  # - title: Subscribe
  #   class: fa fa-rss
  #   href: https://github.com/godpan

